# Form implementation generated from reading ui file 'ui/MainCal.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainInduceGUI(object):
    def setupUi(self, MainInduceGUI):
        MainInduceGUI.setObjectName("MainInduceGUI")
        MainInduceGUI.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainInduceGUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainInduceGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 70, 411, 161))
        self.label.setObjectName("label")
        MainInduceGUI.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainInduceGUI)
        font = QtGui.QFont()
        font.setFamily("Iosevka Term Semibold")
        font.setBold(True)
        self.toolBar.setFont(font)
        self.toolBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainInduceGUI.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionHelp = QtGui.QAction(MainInduceGUI)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\images/help.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHelp.setIcon(icon1)
        self.actionHelp.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionHelp.setVisible(True)
        self.actionHelp.setIconVisibleInMenu(True)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_US = QtGui.QAction(MainInduceGUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\images/about_us.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAbout_US.setIcon(icon2)
        self.actionAbout_US.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAbout_US.setObjectName("actionAbout_US")
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout_US)

        self.retranslateUi(MainInduceGUI)
        QtCore.QMetaObject.connectSlotsByName(MainInduceGUI)

    def retranslateUi(self, MainInduceGUI):
        _translate = QtCore.QCoreApplication.translate
        MainInduceGUI.setWindowTitle(_translate("MainInduceGUI", "Induced Voltage Calculator"))
        self.label.setText(_translate("MainInduceGUI", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("MainInduceGUI", "toolBar"))
        self.actionHelp.setText(_translate("MainInduceGUI", "Help"))
        self.actionAbout_US.setText(_translate("MainInduceGUI", "About Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainInduceGUI = QtWidgets.QMainWindow()
    ui = Ui_MainInduceGUI()
    ui.setupUi(MainInduceGUI)
    MainInduceGUI.show()
    sys.exit(app.exec())
